name: Ensure All Reviewers Have Approved

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  verify-approvals:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check all requested reviewers have approved
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number || context.payload.pull_request_review?.pull_request?.number;
            const { owner, repo } = context.repo;

            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber,
            });

            const requested = pr.data.requested_reviewers.map(r => r.login);
            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number: prNumber,
            });

            const latestReviews = {};
            for (const review of reviews.data) {
              if (['APPROVED', 'CHANGES_REQUESTED'].includes(review.state)) {
                latestReviews[review.user.login] = review.state;
              }
            }

            const missingApprovals = requested.filter(user => latestReviews[user] !== 'APPROVED');

            if (missingApprovals.length > 0) {
              core.setFailed(`These reviewers have not approved: ${missingApprovals.join(', ')}`);
            } else {
              console.log("✅ All requested reviewers have approved.");
            }
