name: Bug Report
description: Report a bug
title: "[BUG] "
labels: bug
assignees: [] 

body:
  - type: markdown
    attributes:                      
      value: "Please follow the instructions below to submit a bug report."

  - type: input
    id: bug_title
    attributes:
      label: Title
      description: Provide a brief title for your bug report.

  - type: textarea
    id: bug_description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...

  - type: input
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. See error"  

  - type: input
    id: environment_info
    attributes:
      label: Environment
      description: Provide details about your environment (OS, browsers, versions, releases, etc.).
      placeholder: "OS: Windows 10, Browser: Chrome 92"

  - type: input
    id: expected_outcome
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: Expected behavior...

  - type: input
    id: actual_outcome
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: Actual behavior...

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Add any other context, screenshots, or logs relevant to the issue here.

  - type: textarea
    id: initial_remedy_steps
    attributes:
      label: Initial Steps Taken
      description: Describe any steps you've taken to try to remedy the bug.
      placeholder: Describe steps tried (e.g., clearing cache, reinstalling, etc.).
