# Disables the option to create blank issues without a template.
blank_issues_enabled: false

# Array of links that provide additional resources for issue submitters.
contact_links:
  - name: GitHub Discussions
    url: https://github.com/WinetraubLab/collect-virtual-histology-samples/discussions
    description: "Ask questions or start discussions regarding the project."


